projectTitle = "Astral Arsenal"
modId = "astral_arsenal"
githubRepo = "Teamvoided/AstralArsenal"
discordServerInviteId = "KZ5Q364hEg"
authors = [ "Astratine", "WiredTomato", "TheEnderCore", "Blurr", "Mincrafteinstein" ]
majorMinecraftVersion = "1.21"
minecraftVersion = "1.21.1"
fabricLoaderVersion = "0.16.3"
fabricApiVersion = "0.103.0+1.21.1"
fabricLangKotlinVersion = "1.12.1+kotlin.2.0.20"
license = "MIT"
modules = [ ]
modDescription = "A funky combat mod"
# Modmenu badges, values can be: [ library, deprecated ]
badges = [ ]
disableKotlin = false

[mappings]
    # You have 7 mapping types
    # MOJANG: The official Mojang mappings
    # YARN: Yarn mappings
    # PARCHMENT: Parchment mappings
    # QUILT: Quilt mappings
    # MOJPARCH: Parchment layered on top of the official Mojang mappings
    # MOJYARN: Yarn layered on top of the official Mojang mappings
    # CUSTOM: Custom mapping jar. Uses mappings version as file location
    type = "QUILT"
    version = "1.21.1+build.3"
