projectTitle = "Team Voided Template"
modId = "astral_arsenal"
githubRepo = "Teamvoided/TeamVoidedTemplateMod"
discordServerInviteId = "KZ5Q364hEg"
authors = [ "WiredTomato", "TheEnderCore" ]
majorMinecraftVersion = "1.21"
minecraftVersion = "1.21"
fabricLoaderVersion = "0.15.11"
fabricApiVersion = "0.100.3+1.21"
fabricLangKotlinVersion = "1.11.0+kotlin.2.0.0"
license = "MIT"
modules = [ ]
modDescription = "Template Mod Description"
# Modmenu badges, values can be: [ library, deprecated ]
badges = [ ]
disableKotlin = false

[mappings]
    # You have 7 mapping types
    # MOJANG: The official Mojang mappings
    # YARN: Yarn mappings
    # PARCHMENT: Parchment mappings
    # QUILT: Quilt mappings
    # MOJPARCH: Parchment layered on top of the official Mojang mappings
    # MOJYARN: Yarn layered on top of the official Mojang mappings
    # CUSTOM: Custom mapping jar. Uses mappings version as file location
    type = "QUILT"
    version = "1.21+build.2"
